pipeline {
    agent any

    stages {

        stage('Checkout Code') {
            steps {
                echo 'Checking out code'
                checkout scm
            }
        }

        stage('Install Dependencies') {
            steps {
                echo 'Installing Python dependencies'
                sh 'python3 --version'
                sh 'pip3 --version'
                sh 'pip3 install -r app/requirements.txt'
            }
        }

        stage('Run Tests') {
            steps {
                echo 'Running tests'
                sh 'pytest tests/'
            }
        }
    }

    post {
        success {
            echo 'PIPELINE SUCCESS'
        }
        failure {
            echo 'PIPELINE FAILED'
        }
    }
}
