pipeline {
    agent {
        docker {
            image 'python:3.11-slim'
        }
    }

    stages {

        stage('Checkout Code') {
            steps {
                checkout scm
            }
        }

        stage('Install Dependencies') {
            steps {
                sh 'pip install --upgrade pip'
                sh 'pip install -r app/requirements.txt'
            }
        }

        stage('Run Tests') {
            steps {
                sh 'pytest tests'
            }
        }
    }

    post {
        success {
            echo '🎉 BUILD SUCCESS — ALL TESTS PASSED'
        }
        failure {
            echo '❌ BUILD FAILED'
        }
    }
}
