pipeline {
    agent any

    stages {

        stage('Checkout Code') {
            steps {
                echo 'Checking out code'
                checkout scm
            }
        }

        stage('Run Tests in Python Container') {
            steps {
                sh '''
                docker run --rm \
                  -v "$PWD:/app" \
                  -w /app \
                  python:3.11-slim \
                  sh -c "pip install -r app/requirements.txt && pytest tests"
                '''
            }
        }
    }

    post {
        success {
            echo '🎉 PIPELINE SUCCESS'
        }
        failure {
            echo '❌ PIPELINE FAILED'
        }
    }
}
